---
- name: checking connection with windows vm
  hosts: local
  become: false
  become_method: runas
  tasks:
        - name: ping windows vm
          ansible.windows.win_powershell:
            script: |
              Test-Connection -ComputerName 20.231.196.162

